[build]
  functions = "src/netlify/functions"
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[functions]]
  name = "post-news"
  schedule = "*/30 * * * *" # every 30 minutes
