[build]
  functions = "src/netlify/functions"
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "src/netlify/functions"

# HTTP accessible function - no schedule
# [functions."post-news-schedule"]
#   schedule = "*/30 * * * *"